# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Urlautofire.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import Qt

class Ui_Urlfire(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 595)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/UAF_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.Filter = QtWidgets.QLineEdit(self.centralwidget)
        
        self.Filter.setInputMask("")
        self.Filter.setText("")
        self.Filter.setObjectName("Filter")
        self.horizontalLayout_3.addWidget(self.Filter)
        
        
        
        #self.horizontalLayout_3.addWidget(self.Listener)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(30, 24))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icon/UAF_icon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Redo = QtWidgets.QToolButton(self.centralwidget)
        self.Redo.setMaximumSize(QtCore.QSize(30, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Redo.setIcon(icon)
        self.Redo.setIconSize(QtCore.QSize(30, 40))
        self.Redo.setAutoRaise(True)
        self.Redo.setObjectName("Redo")
        self.horizontalLayout_2.addWidget(self.Redo)
        self.Play = QtWidgets.QToolButton(self.centralwidget)
        self.Play.setMaximumSize(QtCore.QSize(30, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play.setIcon(icon1)
        self.Play.setIconSize(QtCore.QSize(30, 40))
        self.Play.setAutoRaise(True)
        self.Play.setObjectName("Play")
        self.horizontalLayout_2.addWidget(self.Play)
        self.Into = QtWidgets.QToolButton(self.centralwidget)
        self.Into.setMaximumSize(QtCore.QSize(30, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/into.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Into.setIcon(icon2)
        self.Into.setIconSize(QtCore.QSize(30, 40))
        self.Into.setAutoRaise(True)
        self.Into.setObjectName("Into")
        self.horizontalLayout_2.addWidget(self.Into)
        self.Pause = QtWidgets.QToolButton(self.centralwidget)
        self.Pause.setMaximumSize(QtCore.QSize(30, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Pause.setIcon(icon3)
        self.Pause.setIconSize(QtCore.QSize(30, 40))
        self.Pause.setAutoRaise(True)
        self.Pause.setObjectName("Pause")
        self.horizontalLayout_2.addWidget(self.Pause)
        self.Breack = QtWidgets.QToolButton(self.centralwidget)
        self.Breack.setMaximumSize(QtCore.QSize(30, 40))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/breack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Breack.setIcon(icon4)
        self.Breack.setIconSize(QtCore.QSize(30, 40))
        self.Breack.setAutoRaise(True)
        self.Breack.setObjectName("Breack")
        self.horizontalLayout_2.addWidget(self.Breack)
        
        self.Listener = QtWidgets.QToolButton(self.centralwidget)
        self.Listener.setMaximumSize(QtCore.QSize(25, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/offline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Listener.setIcon(icon1)
        self.Listener.setIconSize(QtCore.QSize(25, 30))
        self.Listener.setAutoRaise(True)
        self.Listener.setObjectName("Listener")
        self.horizontalLayout_2.addWidget(self.Listener)

        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        # icon5 = QtGui.QIcon()
        # icon5.addPixmap(QtGui.QPixmap(":/icon/corrent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # item.setIcon(icon5)
        
        # icon6 = QtGui.QIcon()
        # icon6.addPixmap(QtGui.QPixmap(":/icon/media-playback-pause-symbolic.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # item.setIcon(icon6)
        # self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 22))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.menufile.addAction(self.actionopen)
        self.menubar.addAction(self.menufile.menuAction())
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle("URL AUTO FIRE ")
        self.label_3.setText(_translate("MainWindow", "FILTER"))
        self.Filter.setToolTip(_translate("MainWindow", "REGEX FILTER"))
        
       
        self.Redo.setShortcut("Ctrl+D")
        self.Play.setShortcut("Ctrl+P")
        self.Into.setShortcut("Ctrl+S")
        self.Listener.setShortcut("Ctrl+L")
        self.Pause.setText(_translate("MainWindow", "..."))
        self.Breack.setShortcut("Ctrl+B")
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionopen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        
        self.listWidget.setSortingEnabled(__sortingEnabled)
import icon_rc
